### ISSUE TITLE
Can't loop with process that doesn't exit.

### ISSUE THREAD

**Issue by reggi** [mateodelnorte/loop-things#12]
I tried to loop using the `onchange` command. Doesn't work. 

`loop "onchange './src/*.js' -- npm run compile"`

**Comment by mateodelnorte** [comment]
What is onchange in this example? Is it a command or an alias? If it's a
command, what does 'which onchange' return?

On Feb 19, 2017 8:44 PM, "Thomas Reggi" <notifications@github.com> wrote:

I tried to loop using the onchange command. Doesn't work.

loop "onchange './src/*.js' -- npm run compile"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mateodelnorte/loop-things/issues/12>, or mute the thread

**Comment by reggi** [comment]
`
➜  wonder git:(master) ✗ which onchange
/Users/thomas/.nvm/versions/node/v7.2.1/bin/onchange
`

It's a node module

`npm install onchange -g`

**Comment by mateodelnorte** [comment]
How are your nvm related global commands ending up on your PATH? Guessing
you have something in your .bashrc/.bash_profile/.zshrc adding their dir.

Can you do both 'env' and 'loop env --include-only .' and paste their
results?


On Feb 19, 2017 10:16 PM, "Thomas Reggi" <notifications@github.com> wrote:

➜ wonder git:(master) ✗ which onchange /Users/thomas/.nvm/versions/
node/v7.2.1/bin/onchange

It's a node module

npm install onchange -g

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mateodelnorte/loop-things/issues/12#issuecomment-280978506>,
or mute the thread

**Comment by reggi** [comment]
MANPATH=/Users/thomas/.nvm/versions/node/v7.2.1/share/man:/usr/local/share/man:/usr/share/man:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man
TERM_PROGRAM=Apple_Terminal
ANDROID_HOME=/Users/thomas/Library/Android/sdk
NVM_CD_FLAGS=-q
TERM=xterm-256color
SHELL=/bin/zsh
TMPDIR=/var/folders/z6/xndn2s5n5r52j7m0bx9vdvdr0000gn/T/
NVM_PATH=/Users/thomas/.nvm/versions/node/v7.2.1/lib/node
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.5VoAkyynx5/Render
TERM_PROGRAM_VERSION=388
TERM_SESSION_ID=454D9262-B564-4C09-AD4A-B1923506D9CF
ZSH=/Users/thomas/.oh-my-zsh
NVM_DIR=/Users/thomas/.nvm
USER=thomas
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.6wzlVxh3NA/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PAGER=less
LSCOLORS=Gxfxcxdxbxegedabagacad
PATH=/Users/thomas/.nvm/versions/node/v7.2.1/bin:/Users/thomas/.bin/terraform_0.6.16_darwin_amd64:/usr/local/terraform/bin:/home/your-user-name/terraform:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/thomas/Library/Android/sdk/tools:/Users/thomas/Library/Android/sdk/platform-tools
_=/Users/thomas/.nvm/versions/node/v7.2.1/lib/node_modules/loop-things/node_modules/.bin/cross-env
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
PWD=/Users/thomas/Desktop/wonder-container/wonder/packages/shopify-request
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
HOME=/Users/thomas
SHLVL=2
LESS=-R
LOGNAME=thomas
LC_CTYPE=en_US.UTF-8
NVM_BIN=/Users/thomas/.nvm/versions/node/v7.2.1/bin
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist

**Comment by reggi** [comment]
@mateodelnorte Have you ever tried top loop with a command that doesn't exit?

**Comment by mateodelnorte** [comment]
misread your title to read "exist". this doesn't make sense for loop. use https://www.npmjs.com/package/concurrently instead.
